version: '3'

volumes: 
  dynamodb_data: 
    external: true

services:
  #angular-ui:
  #  image : bus-company-angular-ui-image
  #  container_name: bus-company-angular-ui   
  #  ports:
  #    - "3000:80"
  #  expose:
  #    - "3000"

  backend-api:
    build : ./bus-company-api/BusCompanyAPI    
    container_name: backend-api
    ports:
      - "4040:4040"
    expose:
      - "4040"

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: bus-company-dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes: 
      - ./dynamodb-data:/data
    ports: 
      - "8000:8000"
    expose: 
      - "8000"